services:
  service1:
    image: redteamcont
    privileged: true
    cap_add:
      - SYS_PTRACE
    # Disable the default seccomp profile to let strace work properly.
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty : true

  # service2:
  #   image: nginx
  #   networks:
  #     - isolated_net
  #     # - external_net

networks:
  isolated_net:
    driver: bridge
    internal: true

  # external_net:
  #   driver: bridge
