[build-system]
requires= ["setuptools <= 61.0"]
build-backend = "setuptools.build_meta"


[project]
name ="RedTeamAgent"
dependencies = [
    "pydantic",
    "openai"
    ]

[project.scripts]
### to do